app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10

  urls:
    gitHubBaseUrl: https://api.github.com/
    stackOverflowBaseUrl: https://api.stackexchange.com/


bot:
  api:
    baseurl: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5050/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui
