app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10

  urls:
    gitHubBaseUrl: https://api.github.com/
    stackOverflowBaseUrl: https://api.stackexchange.com/
  database-access-type: jdbc
  back-off: constant
  retry-codes: 500, 400, 404
  topic-name: updates
  use-queue: true
  bootstrap-server: localhost:9092
  use-github-token: true
  github_token: ${GITHUB_TOKEN}

bot:
  api:
    baseurl: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5050/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui

management:
  server:
    port: 8085
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: /metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
